<?php
/**
 * District5 - Composer library
 *
 * @copyright District5
 *
 * @author District5 YEAR to present
 * @link https://www.district5.co.uk
 *
 * @license MIT License
 */

namespace District5\ComposerTemplate\Collection;

use ArrayIterator;
use District5\ComposerTemplate\Model\Person;

/**
 * @class PersonCollection
 * @package District5\ComposerTemplate\Collection
 */
class PersonCollection extends ArrayIterator
{
    /**
     * @var Person[]
     */
    protected array $people = [];

    /**
     * Return current array entry
     * @link https://php.net/manual/en/arrayiterator.current.php
     * @return Person|null
     */
    public function current(): ?Person
    {
        return parent::current();
    }

    /**
     * @param Person $value
     * @return void
     */
    public function append($value): void
    {
        parent::append($value); // TODO: Change the autogenerated stub
    }
}
